FROM node:20-alpine

# Install Python and Java for code execution
RUN apk add --no-cache python3 openjdk11

WORKDIR /app

COPY package*.json ./
RUN npm install --omit=dev

COPY . .

EXPOSE 5000

CMD ["node", "server.js"]