import { useNavigate } from "react-router-dom";
import { motion } from "framer-motion";

export default function Home() {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen bg-gradient-to-br 
    from-[#0f172a] via-[#0b1a35] to-[#0f172a] text-white">

      {/* HERO SECTION */}
      <div className="flex flex-col items-center justify-center 
      text-center py-24 px-6">

        <motion.div
          animate={{ y: [0, -15, 0] }}
          transition={{ repeat: Infinity, duration: 3 }}
          className="w-40 h-40 mb-8 
          rounded-full bg-gradient-to-br 
          from-blue-500 to-purple-600 
          flex items-center justify-center 
          shadow-[0_0_60px_rgba(99,102,241,0.6)]"
        >
          <div className="relative w-28 h-28 bg-gradient-to-br 
          from-indigo-500 to-purple-500 rounded-full flex 
          items-center justify-center">

            <div className="absolute top-10 left-8 w-4 h-4 bg-white rounded-full"></div>
            <div className="absolute top-10 right-8 w-4 h-4 bg-white rounded-full"></div>
            <div className="absolute bottom-8 w-14 h-6 
            border-b-4 border-white rounded-full"></div>

          </div>
        </motion.div>

        <h1 className="text-5xl font-bold mb-6">
          AI Interview Platform
        </h1>

        <p className="text-gray-300 max-w-xl mb-10 text-lg">
          Prepare for real-world interviews with AI-powered evaluation
          across multiple rounds.
        </p>

        <div className="flex gap-6">
          <button
            onClick={() => navigate("/signup")}
            className="px-8 py-3 rounded-full text-white font-semibold
            bg-gradient-to-r from-blue-500 to-purple-500
            shadow-[0_0_30px_rgba(99,102,241,0.6)]
            hover:scale-105 transition"
          >
            Sign Up
          </button>

          <button
            onClick={() => navigate("/login")}
            className="px-8 py-3 rounded-full font-semibold
            border border-gray-500 hover:bg-white/10 transition"
          >
            Login
          </button>
        </div>
      </div>

      {/* HOW IT WORKS */}
      <div className="py-20 px-6 bg-white/5 backdrop-blur-md">
        <h2 className="text-3xl font-bold text-center mb-16">
          How It Works
        </h2>

        <div className="grid md:grid-cols-3 gap-10 max-w-6xl mx-auto">

          {/* ATS ROUND */}
          <div className="p-8 rounded-2xl bg-white/10 
          border border-white/10 shadow-xl">
            <h3 className="text-xl font-semibold mb-4">
              📄 ATS Resume Analysis
            </h3>
            <ul className="text-gray-300 space-y-2 text-sm">
              <li>• Upload Resume (PDF/DOC)</li>
              <li>• Paste Job Description</li>
              <li>• AI analyzes skill & keyword match</li>
              <li>• Structured score breakdown</li>
              <li>• Radar performance graph</li>
            </ul>
          </div>

          {/* APTITUDE ROUND */}
          <div className="p-8 rounded-2xl bg-white/10 
          border border-white/10 shadow-xl">
            <h3 className="text-xl font-semibold mb-4">
              🧠 Timed Aptitude Test
            </h3>
            <ul className="text-gray-300 space-y-2 text-sm">
              <li>• Random questions generated by backend</li>
              <li>• Timer starts immediately</li>
              <li>• Session locked per attempt</li>
              <li>• Auto-submit when time ends</li>
              <li>• Server-side score validation</li>
            </ul>
          </div>

          {/* SECURITY */}
          <div className="p-8 rounded-2xl bg-white/10 
          border border-white/10 shadow-xl">
            <h3 className="text-xl font-semibold mb-4">
              🔒 Secure Evaluation
            </h3>
            <ul className="text-gray-300 space-y-2 text-sm">
              <li>• Backend timer enforcement</li>
              <li>• Refresh does not reset attempt</li>
              <li>• Score calculated on server</li>
              <li>• Session-based tracking</li>
              <li>• Attempt stored for analysis</li>
            </ul>
          </div>

        </div>
      </div>

      {/* PERFORMANCE INSIGHTS */}
      <div className="py-20 px-6">
        <h2 className="text-3xl font-bold text-center mb-16">
          Detailed Performance Insights
        </h2>

        <div className="grid md:grid-cols-2 gap-10 max-w-5xl mx-auto">

          <div className="p-8 rounded-2xl bg-white/10 border border-white/10 shadow-xl">
            <h3 className="text-xl font-semibold mb-4">ATS Breakdown</h3>
            <ul className="text-gray-300 space-y-2 text-sm">
              <li>• Skill Match Score</li>
              <li>• Keyword Match Score</li>
              <li>• Experience Alignment</li>
              <li>• Formatting Quality</li>
              <li>• Impact Strength</li>
            </ul>
          </div>

          <div className="p-8 rounded-2xl bg-white/10 border border-white/10 shadow-xl">
            <h3 className="text-xl font-semibold mb-4">Aptitude Breakdown</h3>
            <ul className="text-gray-300 space-y-2 text-sm">
              <li>• Accuracy Percentage</li>
              <li>• Time Utilization</li>
              <li>• Category Performance</li>
              <li>• Difficulty Analysis</li>
              <li>• Overall Score</li>
            </ul>
          </div>

        </div>
      </div>

      {/* TERMS & CONDITIONS */}
      <div className="py-20 px-6 bg-white/5 backdrop-blur-md">
        <h2 className="text-3xl font-bold text-center mb-12">
          Terms & Conditions
        </h2>

        <div className="max-w-4xl mx-auto space-y-6 text-gray-300 text-sm">

          <div>
            <h4 className="font-semibold text-white mb-2">
              Test Integrity
            </h4>
            <p>
              ⌛Timer cannot be reset once started. Refreshing does not create a new attempt.
              Scores are calculated securely on the backend.
            </p>
          </div>

          <div>
            <h4 className="font-semibold text-white mb-2">
              AI Analysis Disclaimer
            </h4>
            <p>
              🤖AI feedback is advisory only. Scores are estimation-based and
              do not guarantee job placement.
            </p>
          </div>

          <div>
            <h4 className="font-semibold text-white mb-2">
              Data Usage
            </h4>
            <p>
              📃Resume data is used solely for analysis. No third-party sharing.
              Test results may be stored for performance tracking.
            </p>
          </div>

          <div>
            <h4 className="font-semibold text-white mb-2">
              Fair Usage Policy
            </h4>
            <p>
              💣Do not attempt to manipulate scoring or exploit refresh/network behavior.
              Misuse may result in account restriction.
            </p>
          </div>

        </div>
      </div>

    </div>
  );
}